export const GET_PRODUCTS_SUCCES = "GET_PRODUCTS_SUCCES";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
